# Emscripten PATH, modify this as needed.
EMSCRIPTEN_HOME = ".\compiler\emscripten\1.37.21"

# Python3 binary
PYTHON3 = "C:\Users\Nathan\AppData\Local\Programs\Python\Python36-32\python.exe"

# cpplint binary
CPPLINT = cpplint
